### ISSUE TITLE
Negative repeat count does nothing warnings 

### ISSUE THREAD

**Issue by jamadam** [markov2/perl5-Mail-Box#2]
Hi. Thank you for your efforts on the module.

I'd like to report an issue on the latest release of the module. Since upgrading the module from v3.003 to v3.005, I started to encounter following warnings.

> Negative repeat count does nothing at /opt/perlbrew/perls/perl-5.22.1/lib/site_perl/5.22.1/Mail/Box/Maildir.pm line 244.

The exact position on the latest source code is following.

https://github.com/markov2/perl5-Mail-Box/blob/4c957bed8e7dff247a5871e7ebc8ff236ae79437/lib/Mail/Box/Maildir.pm#L315

The warning has been introduced at perl-5.21.

http://perldoc.perl.org/perl5211delta.html#New-Diagnostics

I wonder if the module could prevent the warnings. I haven't figure out the root cause of the negative value, though.

Perl: 5.22.1
Postfix: 2.6.6
CentOS release 6.9

**Comment by markov2** [comment]
I added 'use warnings' to the file, and now it reports a sleeping bug ;-)

"date +%s" will show you that timestamps currently have 10 digits, not 9.
